Repository boa-dev/temporal, pull requests merged in 2024-02, with the labels that each got.

#6 Create LICENSE-Apache
  .github/workflows/rust.yml
  LICENSE-Apache
Labels: C-meta

#16 Adding a `docs` directory
  docs/README.md
  docs/design/initial-api-concept.md
Labels: C-documentation

#18 Simplify Temporal APIs
  src/components/calendar.rs
  src/components/date.rs
  src/components/datetime.rs
  src/components/duration.rs
  src/components/duration/date.rs
  src/components/tz.rs
  src/components/zoneddatetime.rs
Labels: C-enhancement

#26 Setup publish CI
  .github/release.yml
  .github/workflows/release.yml
  Cargo.toml
  cliff.toml
Labels: C-meta

#24 Implement `Duration::round` and some general updates/fixes
  src/components/calendar.rs
  src/components/date.rs
  src/components/duration.rs
  src/components/duration/date.rs
  src/components/duration/normalized.rs
  src/components/duration/tests.rs
  src/components/duration/time.rs
  src/components/instant.rs
  src/components/time.rs
  src/iso.rs
  src/options.rs
  src/parser/tests.rs
  src/utils.rs
Labels: C-enhancement

#27 Add first changelog
  CHANGELOG.md
Labels: C-meta

#28 Remove keywords from Cargo.toml
  CHANGELOG.md
  Cargo.toml
Labels: C-meta
