Repository boa-dev/temporal, pull requests merged in 2024-12, with the labels that each got.

#121 Patch the now test per matrix discussion
  Cargo.lock
  src/components/now.rs
Labels: C-internal

#115 Implement `PartialZonedDateTime` and `from_partial` and `from_str` for `ZonedDateTime`
  src/components/date.rs
  src/components/datetime.rs
  src/components/duration/normalized.rs
  src/components/instant.rs
  src/components/mod.rs
  src/components/now.rs
  src/components/time.rs
  src/components/tz.rs
  src/components/zoneddatetime.rs
  src/iso.rs
  src/lib.rs
  src/options.rs
  src/tzdb.rs
Labels: C-enhancement

#123 Add now feature flag
  Cargo.toml
  src/components/mod.rs
  src/lib.rs
  src/sys.rs
Labels: C-enhancement

#126 Migrate repo to workspace
  .github/workflows/release.yml
  .github/workflows/rust.yml
  Cargo.toml
Labels: C-meta

#125 Adjust compilation configuration of tzdb to target_family from target_os
  src/tzdb.rs
Labels: C-bug

#128 Fix bug introduced by `EpochNanoseconds` + adjust tests to catch better
  src/components/date.rs
  src/components/datetime.rs
  src/iso.rs
Labels: C-bug

#129 Add to-x methods and with-x methods to ZonedDateTime
  src/components/instant.rs
  src/components/zoneddatetime.rs
Labels: C-enhancement

#137 Update try_new, new, and new_with_overflow integer type
  src/components/calendar.rs
  src/components/calendar/types.rs
  src/components/date.rs
  src/components/datetime.rs
  src/components/duration/normalized.rs
  src/components/instant.rs
  src/components/month_day.rs
  src/components/time.rs
  src/components/year_month.rs
  src/components/zoneddatetime.rs
  src/iso.rs
  src/utils.rs
Labels: C-api

#146 Fix RoundingMode::truncation to UnsignedRoundingMode mapping
  src/components/time.rs
  src/options.rs
Labels: C-bug
