Repository boa-dev/temporal, pull requests merged in 2024-07, with the labels that each got.

#69 Use groups in dependabot updates
  .github/dependabot.yml
Labels: C-meta, dependencies

#66 Remove `CalendarProtocol` and `TimeZoneProtocol`
  .gitignore
  Cargo.toml
  src/components/calendar.rs
  src/components/date.rs
  src/components/datetime.rs
  src/components/duration.rs
  src/components/duration/date.rs
  src/components/duration/tests.rs
  src/components/month_day.rs
  src/components/tz.rs
  src/components/year_month.rs
  src/components/zoneddatetime.rs
  src/fields.rs
  src/iso.rs
  src/options.rs
Labels: C-api, C-internal

#75 Implement PartialEq and Eq for `Calendar`, `Date`, and `DateTime`
  src/components/calendar.rs
  src/components/date.rs
  src/components/datetime.rs
Labels: C-api

#74 Implement add and subtract methods for Duration
  src/components/duration.rs
  src/components/duration/tests.rs
Labels: C-enhancement, C-api

#81 Add some missing trait implementations
  src/components/calendar.rs
  src/components/date.rs
  src/components/datetime.rs
  src/components/duration.rs
  src/components/duration/date.rs
  src/components/duration/tests.rs
  src/components/time.rs
  src/parsers.rs
Labels: C-api

#84 Add `with_*` methods to `Date` and `DateTime`
  src/components/calendar.rs
  src/components/date.rs
  src/components/datetime.rs
Labels: C-enhancement, C-api

#83 Implement `DateTime` diffing methods `Until` and `Since`
  src/components/date.rs
  src/components/datetime.rs
  src/rounding.rs
Labels: C-enhancement, C-api

#82 Implement compare functionality and some more traits
  src/components/date.rs
  src/components/datetime.rs
  src/components/tz.rs
  src/components/zoneddatetime.rs
Labels: C-enhancement, C-api

#85 Updates to instant and its methods
  src/components/datetime.rs
  src/components/duration/normalized.rs
  src/components/duration/time.rs
  src/components/instant.rs
  src/components/zoneddatetime.rs
  src/iso.rs
  src/options.rs
  src/parsers.rs
Labels: C-enhancement, C-internal

#87 Refactor `TemporalFields` interface and add `FieldsKey` enum
  src/components/calendar.rs
  src/fields.rs
Labels: C-internal

#86 Update `Duration` types to use a `FiniteF64` instead of `f64` primitive.
  src/components/calendar.rs
  src/components/date.rs
  src/components/datetime.rs
  src/components/duration.rs
  src/components/duration/date.rs
  src/components/duration/normalized.rs
  src/components/duration/tests.rs
  src/components/duration/time.rs
  src/components/instant.rs
  src/components/time.rs
  src/iso.rs
  src/lib.rs
  src/primitive.rs
Labels: C-api, C-internal
