Repository boa-dev/temporal, pull requests merged in 2024-06, with the labels that each got.

#54 Cleanup rounding increment usages with new struct
  src/components/instant.rs
  src/components/time.rs
  src/iso.rs
  src/options.rs
  src/options/increment.rs
  src/utils.rs
Labels: C-enhancement, C-internal

#48 Patch `(un)balance_relative` to avoid panicking
  src/components/duration/date.rs
Labels: C-bug

#53 Update increment rounding functionality
  src/components/duration.rs
  src/components/duration/date.rs
  src/components/duration/normalized.rs
  src/components/duration/tests.rs
  src/components/duration/time.rs
  src/components/instant.rs
  src/iso.rs
  src/lib.rs
  src/options.rs
  src/options/increment.rs
  src/rounding.rs
  src/utils.rs
Labels: C-enhancement, C-internal

#56 Implement the `toYearMonth`, `toMonthDay`, and `toDateTime` for `Date` component
  src/components/date.rs
  src/components/time.rs
  src/fields.rs
Labels: C-internal

#57 Fix rounding when the dividend is smaller than the divisor
  src/components/time.rs
  src/rounding.rs
Labels: C-bug, C-internal

#58 Ensure parsing throws when duplicate calendar is critical
  src/parsers.rs
Labels: C-bug, C-internal

#61 Avoid overflowing when calling `NormalizedTimeDuration::add_days`
  src/components/duration/normalized.rs
  src/components/duration/tests.rs
Labels: C-bug, C-internal

#62 Reject `IsoDate` when outside the allowed range
  src/components/date.rs
  src/iso.rs
  src/rounding.rs
Labels: C-bug, C-internal

#63 Ensure parsing throws with unknown critical annotations
  src/components/date.rs
  src/parsers.rs
Labels: C-bug, C-internal
