Repository boa-dev/temporal, pull requests merged in 2025-06, with the labels that each got.

#356 Stop depending on `is_dst` for calculations
  src/builtins/core/timezone.rs
  src/parsers.rs
  src/provider.rs
  src/tzdb.rs
Labels: C-api, C-internal

#359 Add convenience methods for constructing FFI datetime types from milliseconds
  temporal_capi/bindings/c/PlainDate.h
  temporal_capi/bindings/c/PlainDateTime.h
  temporal_capi/bindings/c/PlainTime.h
  temporal_capi/bindings/c/ZonedDateTime.h
  temporal_capi/bindings/cpp/temporal_rs/PlainDate.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainDate.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainDateTime.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainDateTime.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainTime.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainTime.hpp
  temporal_capi/bindings/cpp/temporal_rs/ZonedDateTime.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/ZonedDateTime.hpp
  temporal_capi/src/plain_date.rs
  temporal_capi/src/plain_date_time.rs
  temporal_capi/src/plain_time.rs
  temporal_capi/src/zoned_date_time.rs
Labels: C-FFI

#257 Implement zoneinfo parsing/compilation and add TZif structs
  Cargo.lock
  Cargo.toml
  bakeddata/src/main.rs
  provider/Cargo.toml
  provider/src/lib.rs
  provider/src/tzdb.rs
  provider/src/tzif.rs
  src/tzdb.rs
  zoneinfo-test-gen/Cargo.toml
  zoneinfo-test-gen/README.md
  zoneinfo-test-gen/src/main.rs
  zoneinfo/Cargo.toml
  zoneinfo/src/compiler.rs
  zoneinfo/src/lib.rs
  zoneinfo/src/parser.rs
  zoneinfo/src/rule.rs
  zoneinfo/src/types.rs
  zoneinfo/src/tzif.rs
  zoneinfo/src/utils.rs
  zoneinfo/src/zone.rs
  zoneinfo/tests/data/america-anchorage.json
  zoneinfo/tests/data/america-chicago.json
  zoneinfo/tests/data/america-new_york.json
  zoneinfo/tests/data/antarctica-troll.json
  zoneinfo/tests/data/australia-lord_howe.json
  zoneinfo/tests/data/australia-sydney.json
  zoneinfo/tests/data/europe-berlin.json
  zoneinfo/tests/data/europe-dublin.json
  zoneinfo/tests/data/europe-london.json
  zoneinfo/tests/data/europe-paris.json
  zoneinfo/tests/data/europe-riga.json
  zoneinfo/tests/data/rearguard/europe-dublin.json
  zoneinfo/tests/test_datagen.rs
  zoneinfo/tests/zoneinfo
Labels: providers

#344 [capi] Add stringifier/cloning to timezones
  temporal_capi/bindings/c/TimeZone.h
  temporal_capi/bindings/cpp/temporal_rs/TimeZone.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/TimeZone.hpp
  temporal_capi/src/time_zone.rs
Labels: C-FFI

#360 Add documentation and doctests for builtins
  src/builtins/core/date.rs
  src/builtins/core/datetime.rs
  src/builtins/core/duration.rs
  src/builtins/core/instant.rs
  src/builtins/core/month_day.rs
  src/builtins/core/time.rs
  src/builtins/core/year_month.rs
  src/builtins/core/zoneddatetime.rs
Labels: C-documentation

#376 Re-add try_from_offset_str
  temporal_capi/bindings/c/TimeZone.h
  temporal_capi/bindings/cpp/temporal_rs/TimeZone.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/TimeZone.hpp
  temporal_capi/src/time_zone.rs
Labels: C-api
