Repository boa-dev/temporal, pull requests merged in 2025-02, with the labels that each got.

#190 Small API cleanup and a couple dev docs updates
  docs/architecture.md
  src/builtins/compiled/instant.rs
  src/builtins/core/instant.rs
  src/builtins/core/time.rs
  temporal_capi/src/plain_time.rs
Labels: C-api

#183 Reimplement Unit Group with different approach
  src/builtins/core/date.rs
  src/builtins/core/datetime.rs
  src/builtins/core/instant.rs
  src/builtins/core/time.rs
  src/builtins/core/zoneddatetime.rs
  src/options.rs
Labels: C-internal

#182 Cleanup `Now` API in favor of system defined implementations
  Cargo.toml
  src/builtins/compiled/now.rs
  src/builtins/core/mod.rs
  src/builtins/core/now.rs
  src/lib.rs
  src/sys.rs
Labels: C-enhancement, C-api

#191 Fix calendar parsing on `from_str` implementation
  src/builtins/core/calendar.rs
  src/parsers.rs
Labels: C-bug

#195 Fix handling of leap seconds in parsing
  src/builtins/core/datetime.rs
  src/builtins/core/instant.rs
  src/builtins/core/time.rs
  src/builtins/core/zoneddatetime.rs
  src/iso.rs
  src/options/relative_to.rs
Labels: C-bug, C-internal

#194 Update unit group validation to handle rounding options
  src/builtins/core/datetime.rs
  src/options.rs
Labels: C-bug, C-internal

#196 Update time parsing to error on dup critical calendars
  src/parsers.rs
Labels: C-bug, C-internal

#197 Fix parsing bugs related to UTC Designator usage
  src/builtins/core/time.rs
  src/builtins/core/zoneddatetime.rs
  src/parsers.rs
Labels: C-bug

#205 PlainYearMonth parsing and Calendar field resolution cleanup/fixes
  src/builtins/core/calendar.rs
  src/builtins/core/calendar/types.rs
  src/builtins/core/year_month.rs
  src/iso.rs
  src/parsers.rs
Labels: C-bug

#211 Reject non-iso calendar in `YearMonth::from_str` and `MonthDay::from_str`
  src/builtins/core/month_day.rs
  src/builtins/core/year_month.rs
Labels: C-bug

#212 Test all combinations of features
  .github/dependabot.yml
  .github/release.yml
  .github/workflows/rust.yml
  Cargo.toml
  src/builtins/compiled/now.rs
  src/builtins/core/now.rs
Labels: C-meta, C-internal

#206 implement utility methods on partial structs
  src/builtins/core/calendar.rs
  src/builtins/core/date.rs
  src/builtins/core/datetime.rs
  src/builtins/core/duration.rs
  src/builtins/core/time.rs
  src/builtins/core/zoneddatetime.rs
Labels: C-enhancement, C-api

#214 Implement posix resolution for month-week-day
  src/iso.rs
  src/tzdb.rs
  src/utils.rs
Labels: C-enhancement, C-internal

#203 Add `GetNamedTimeZoneTransition` method to TimeZoneProvider trait
  src/builtins/compiled/zoneddatetime.rs
  src/builtins/core/zoneddatetime.rs
  src/provider.rs
  src/tzdb.rs
Labels: C-enhancement, C-api

#219 Update ixdtf to 0.4.0
  Cargo.lock
  Cargo.toml
  src/builtins/core/duration.rs
  src/builtins/core/instant.rs
  src/builtins/core/zoneddatetime.rs
  src/iso.rs
  src/options/relative_to.rs
  src/parsers.rs
Labels: C-internal

#221 Fix `Instant::epoch_milliseconds` for values before Epoch
  src/builtins/core/instant.rs
Labels: C-bug, C-internal

#207 Add `UtcOffset` struct for `PartialZonedDateTime`
  src/builtins/core/timezone.rs
  src/builtins/core/zoneddatetime.rs
  src/lib.rs
  src/options/relative_to.rs
  src/parsers/timezone.rs
Labels: C-enhancement
