Repository boa-dev/temporal, pull requests merged in 2025-07, with the labels that each got.

#392 Remove UTC designator check from time zone parsing
  src/builtins/compiled/zoneddatetime.rs
  src/builtins/core/timezone.rs
  src/builtins/core/zoneddatetime.rs
Labels: C-bug, C-internal

#398 Fix the bakedata provider path
  tools/bakeddata/src/main.rs
Labels: C-bug, C-internal

#265 Add POSIX time zone string support to zoneinfo
  Cargo.lock
  provider/Cargo.toml
  provider/src/lib.rs
  provider/src/posix.rs
  provider/src/tzdb.rs
  provider/src/tzif.rs
  zoneinfo/src/compiler.rs
  zoneinfo/src/lib.rs
  zoneinfo/src/posix.rs
  zoneinfo/src/rule.rs
  zoneinfo/src/types.rs
  zoneinfo/src/zone.rs
  zoneinfo/tests/posix.rs
  zoneinfo/tests/zoneinfo
Labels: C-enhancement, providers

#375 [capi] Add from_utf8/from_utf16 for OwnedRelativeTo
  temporal_capi/bindings/c/OwnedRelativeTo.h
  temporal_capi/bindings/cpp/temporal_rs/OwnedRelativeTo.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/OwnedRelativeTo.hpp
  temporal_capi/src/zoned_date_time.rs
Labels: C-FFI

#422 Parse both zoned and unzoned date times in relativeTo
  src/options/relative_to.rs
Labels: test262

#470 Fix overflow when validating Duration
  src/builtins/core/duration.rs
Labels: C-bug, test262
