Repository boa-dev/temporal, pull requests merged in 2025-03, with the labels that each got.

#225 Fix bugs around validating diffing units
  src/options.rs
Labels: C-bug, C-internal

#223 Fixes for `EpochNanosecond`s and `Offset` parsing
  src/builtins/core/datetime.rs
  src/builtins/core/instant.rs
  src/builtins/core/timezone.rs
  src/builtins/core/zoneddatetime.rs
  src/epoch_nanoseconds.rs
  src/iso.rs
  src/parsers/timezone.rs
  temporal_capi/src/instant.rs
Labels: C-bug

#235 Clean up API ergonomics for calendar methods
  README.md
  src/builtins/core/calendar.rs
  src/builtins/core/date.rs
  src/builtins/core/datetime.rs
  src/builtins/core/month_day.rs
  src/builtins/core/year_month.rs
  src/builtins/core/zoneddatetime.rs
  src/iso.rs
  src/lib.rs
  temporal_capi/bindings/cpp/temporal_rs/Calendar.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/Calendar.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainDate.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainDate.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainDateTime.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainDateTime.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainMonthDay.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainMonthDay.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainYearMonth.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainYearMonth.hpp
  temporal_capi/src/calendar.rs
  temporal_capi/src/plain_date.rs
  temporal_capi/src/plain_date_time.rs
  temporal_capi/src/plain_month_day.rs
  temporal_capi/src/plain_year_month.rs
Labels: C-api

#237 Adjustments to `toPlainYearMonth` and `toPlainMonthDay` methods on PlainDate
  src/builtins/core/date.rs
  temporal_capi/bindings/cpp/temporal_rs/PlainDate.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainDate.hpp
  temporal_capi/src/plain_date.rs
Labels: C-api

#238 Prepare temporal_capi for publish
  Cargo.lock
  Cargo.toml
  cliff.toml
  diplomat-gen/Cargo.toml
  temporal_capi/.gitattributes
  temporal_capi/Cargo.toml
  temporal_capi/README.md
  temporal_capi/src/lib.rs
Labels: C-meta

#239 chore(release): bump version and update CHANGELOG.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  cliff.toml
Labels: C-documentation, C-meta

#240 chore(release): fix description of temporal_capi
  temporal_capi/Cargo.toml
Labels: C-meta

#247 Add licenses to `temporal_capi` and `temporal_rs` for publish
  Cargo.toml
  temporal_capi/Cargo.toml
  temporal_capi/LICENSE-Apache
  temporal_capi/LICENSE-MIT
Labels: C-internal

#243 Rename methods on `Now` and add a test
  src/builtins/compiled/now.rs
  src/builtins/core/now.rs
Labels: C-api

#248 chore(release): bump version to 0.0.6 and update CHANGELOG.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: C-meta

#251 Implement IANA normalizer baked data provider
  .gitignore
  Cargo.lock
  Cargo.toml
  bakeddata/Cargo.toml
  bakeddata/README.md
  bakeddata/src/main.rs
  provider/Cargo.toml
  provider/src/data/debug/iana_normalizer.json
  provider/src/data/iana_normalizer.rs.data
  provider/src/data/mod.rs
  provider/src/lib.rs
  provider/src/tzdb.rs
  src/tzdb.rs
Labels: C-enhancement, C-internal

#253 Add intro documentation to ZonedDateTime and PlainDateTime
  src/builtins/core/datetime.rs
  src/builtins/core/zoneddatetime.rs
Labels: C-documentation
