Repository boa-dev/temporal, pull requests merged in 2025-05, with the labels that each got.

#278 Impl round_with_provider for ZonedDateTIme
  src/builtins/compiled/zoneddatetime.rs
  src/builtins/core/zoneddatetime.rs
Labels: C-enhancement

#269 Expose equals and compare over FFI
  temporal_capi/bindings/cpp/temporal_rs/PlainDate.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainDate.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainDateTime.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainDateTime.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainMonthDay.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainMonthDay.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainTime.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainTime.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainYearMonth.d.hpp
  temporal_capi/bindings/cpp/temporal_rs/PlainYearMonth.hpp
  temporal_capi/src/plain_date.rs
  temporal_capi/src/plain_date_time.rs
  temporal_capi/src/plain_month_day.rs
  temporal_capi/src/plain_time.rs
  temporal_capi/src/plain_year_month.rs
Labels: C-enhancement, C-FFI

#263 Add ISO specific constructors to builtins
  src/builtins/core/date.rs
  src/builtins/core/datetime.rs
  src/builtins/core/year_month.rs
  src/builtins/core/zoneddatetime.rs
Labels: C-api

#187 Add Eq, Ord impls on FiniteF64
  src/primitive.rs
Labels: C-enhancement, C-api

#284 Add `PlainMonthDay` method + clean up
  src/builtins/core/month_day.rs
Labels: C-documentation, C-enhancement

#302 Patch regression in calendar parsing
  src/builtins/core/calendar.rs
Labels: C-bug

#317 Align `Duration.prototype.round()` to latest specification
  src/builtins/core/duration.rs
  src/builtins/core/duration/normalized.rs
  src/builtins/core/time.rs
  src/options.rs
Labels: C-enhancement, C-internal
