Repository boa-dev/temporal, pull requests merged in 2025-01, with the labels that each got.

#153 Implement support for `to_string` and implement `PlainDate::to_string`
  Cargo.lock
  Cargo.toml
  src/components/date.rs
  src/components/timezone.rs
  src/options.rs
  src/parsers.rs
Labels: C-enhancement

#156 Fix edge case for disambiguating `ZonedDateTime`s on DSTs skipping midnight
  src/components/timezone.rs
  src/components/zoneddatetime.rs
  src/tzdb.rs
Labels: C-bug

#157 Fixing panics in test262 when running in debug mode
  src/components/instant.rs
  src/components/zoneddatetime.rs
  src/options/relative_to.rs
  src/rounding.rs
Labels: C-bug

#158 Add an MSRV check to CI
  .github/workflows/rust.yml
  Cargo.toml
  src/components/zoneddatetime.rs
Labels: C-enhancement, C-meta

#159 Implement correct resolving of `getStartOfDay`
  src/components/timezone.rs
  src/components/zoneddatetime.rs
  src/tzdb.rs
Labels: C-bug, C-enhancement

#168 API cleanup, visibility updates, and tech debt cleanup
  src/components/calendar.rs
  src/components/date.rs
  src/components/datetime.rs
  src/components/duration.rs
  src/components/duration/normalized.rs
  src/components/instant.rs
  src/components/mod.rs
  src/components/month_day.rs
  src/components/now.rs
  src/components/timezone.rs
  src/components/year_month.rs
  src/components/zoneddatetime.rs
  src/lib.rs
  src/options/relative_to.rs
  src/tzdb.rs
Labels: C-api, C-internal

#164 Implement to_string functionality and methods for `Duration`, `PlainYearMonth`, and `PlainMonthDay`
  Cargo.lock
  Cargo.toml
  src/components/duration.rs
  src/components/duration/normalized.rs
  src/components/duration/tests.rs
  src/components/month_day.rs
  src/components/timezone.rs
  src/components/year_month.rs
  src/parsers.rs
  src/primitive.rs
Labels: C-enhancement

#171 Remove `UnitGroup` addition
  src/components/date.rs
  src/components/datetime.rs
  src/components/instant.rs
  src/components/time.rs
  src/components/zoneddatetime.rs
  src/options.rs
Labels: C-bug

#163 Set up basic diplomat workflow
  Cargo.lock
  Cargo.toml
  diplomat-gen/Cargo.toml
  diplomat-gen/src/main.rs
  temporal_capi/Cargo.toml
  temporal_capi/bindings/cpp/diplomat_runtime.hpp
  temporal_capi/src/calendar.rs
  temporal_capi/src/error.rs
  temporal_capi/src/lib.rs
  temporal_capi/src/options.rs
  temporal_capi/src/plain_date.rs
Labels: C-enhancement

#173 Fix `Duration` parsing not returning a range error.
  src/components/duration.rs
Labels: C-bug

#181 Rework library restructure to remove wrapper types
  Cargo.toml
  src/builtins/compiled/duration.rs
  src/builtins/compiled/duration/tests.rs
  src/builtins/compiled/instant.rs
  src/builtins/compiled/mod.rs
  src/builtins/compiled/now.rs
  src/builtins/compiled/timezone.rs
  src/builtins/compiled/zoneddatetime.rs
  src/builtins/core/duration.rs
  src/builtins/core/mod.rs
  src/builtins/core/options.rs
  src/builtins/core/timezone.rs
  src/builtins/core/zoneddatetime.rs
  src/builtins/mod.rs
  src/builtins/native/date.rs
  src/builtins/native/datetime.rs
  src/builtins/native/duration.rs
  src/builtins/native/instant.rs
  src/builtins/native/mod.rs
  src/builtins/native/now.rs
  src/builtins/native/options.rs
  src/builtins/native/time.rs
  src/builtins/native/timezone.rs
  src/lib.rs
  src/options/relative_to.rs
Labels: C-api

#176 Add some testing / debugging docs
  CONTRIBUTING.md
  docs/testing.md
Labels: C-internal

#174 Fix Instant parsing by handling order of operations and properly balance `IsoDateTime`
  src/builtins/core/instant.rs
Labels: C-bug

#179 Add some FFI tests
  .github/workflows/rust.yml
  temporal_capi/.gitignore
  temporal_capi/cpp_tests/Makefile
  temporal_capi/cpp_tests/simple.cpp
Labels: C-enhancement, C-FFI

#184 Fix the typo that's returning milliseconds instead of microseconds
  src/builtins/core/zoneddatetime.rs
Labels: C-bug

#178 More FFI APIs
  temporal_capi/Cargo.toml
  temporal_capi/src/duration.rs
  temporal_capi/src/lib.rs
  temporal_capi/src/options.rs
  temporal_capi/src/plain_date.rs
  temporal_capi/src/plain_date_time.rs
  temporal_capi/src/plain_month_day.rs
  temporal_capi/src/plain_time.rs
  temporal_capi/src/plain_year_month.rs
Labels: C-enhancement, C-FFI

#175 Add Eq and Ord for PlainYearMonth + Eq for PlainMonthDay
  src/builtins/core/date.rs
  src/builtins/core/datetime.rs
  src/builtins/core/month_day.rs
  src/builtins/core/year_month.rs
  src/builtins/core/zoneddatetime.rs
  temporal_capi/src/plain_year_month.rs
Labels: C-enhancement
